package pl.jclab.refio.core.models.streaming

import pl.jclab.refio.core.llm.LLMUsage
import pl.jclab.refio.core.models.api.PlanningResponse

/**
 * Streaming API models for chat streaming.
 *
 * Note: StreamChunk is now defined in StreamTypes.kt
 */

/**
 * Streaming response from ChatService.
 *
 * Flow emits multiple chunks during streaming:
 * 1. Initial chunk (messageId, isStart=true)
 * 2. Content chunks (delta + accumulated content)
 * 3. Final chunk (usage, cost, isComplete=true)
 *
 * @param messageId Temporary message ID (UUID)
 * @param delta New content in this chunk
 * @param content Full accumulated content so far
 * @param isStart True if this is the first chunk
 * @param isComplete True if streaming is complete
 * @param usage Token usage (only in final chunk)
 * @param cost Estimated cost in USD (only in final chunk)
 */
data class ChatStreamResponse(
    val messageId: String,
    val delta: String,
    val content: String,
    val isStart: Boolean = false,
    val isComplete: Boolean = false,
    val usage: LLMUsage? = null,
    val cost: Double? = null
)

/**
 * Streaming API models for Plan/Agent mode streaming.
 */

/**
 * Stream type for planning operations
 */
enum class PlanStreamType {
    STREAMING,      // Raw LLM chunks (JSON)
    PARSED,         // Parsed plan + subtasks created
    COMPLETE        // Final chunk with metrics
}

/**
 * Streaming response from PlanningService.
 *
 * Flow emits multiple chunks during planning:
 * 1. STREAMING chunks (raw JSON content as it streams)
 * 2. PARSED chunk (plan parsed, subtasks created)
 * 3. COMPLETE chunk (final with usage metrics)
 *
 * @param type Type of chunk
 * @param delta New content in this chunk (for STREAMING)
 * @param content Full accumulated content
 * @param parsedPlan Parsed planning response (for PARSED/COMPLETE)
 * @param isComplete True if streaming is complete
 * @param usage Token usage (only in COMPLETE)
 * @param cost Estimated cost in USD (only in COMPLETE)
 * @param error Error details if operation failed
 */
data class PlanStreamResponse(
    val type: PlanStreamType,
    val delta: String = "",
    val content: String = "",
    val parsedPlan: PlanningResponse? = null,
    val isComplete: Boolean = false,
    val usage: LLMUsage? = null,
    val cost: Double = 0.0,
    val error: ErrorDetail? = null
)

/**
 * Stream type for step planning operations
 */
enum class StepPlanStreamType {
    STREAMING,      // Raw LLM chunks (JSON with tool/args)
    PARSED,         // Parsed tool call
    COMPLETE        // Final chunk with metrics
}

/**
 * Streaming response from StepPlanner.
 *
 * @param type Type of chunk
 * @param delta New content in this chunk (for STREAMING)
 * @param content Full accumulated content
 * @param toolCall Parsed tool call (for PARSED/COMPLETE)
 * @param planDecision Decision details: suggested vs selected (for PARSED/COMPLETE)
 * @param isComplete True if streaming is complete
 * @param usage Token usage (only in COMPLETE)
 * @param cost Estimated cost in USD (only in COMPLETE)
 */
data class StepPlanStreamResponse(
    val type: StepPlanStreamType,
    val delta: String = "",
    val content: String = "",
    val toolCall: ToolCallSpec? = null,
    val planDecision: PlanDecisionInfo? = null,
    val isComplete: Boolean = false,
    val usage: LLMUsage? = null,
    val cost: Double = 0.0
)

/**
 * Tool call specification from step planning
 */
data class ToolCallSpec(
    val name: String,
    val params: Map<String, Any>,
    val expectedOutput: String? = null
)

/**
 * Details about planning decision - what was suggested vs what was selected by LLM.
 *
 * Provides transparency into how LLM modified the initial suggestion:
 * - intent: High-level description of what step should achieve
 * - suggestedTool: Tool name from PlanningService (initial plan)
 * - suggestedParams: Parameters from initial plan
 * - selectedTool: Tool name chosen by LLM (may differ)
 * - selectedParams: Parameters generated by LLM (may differ)
 * - reasoning: LLM's explanation for any changes (if modified)
 * - wasModified: True if LLM changed tool or params from suggestion
 */
data class PlanDecisionInfo(
    val intent: String,
    val suggestedTool: String,
    val suggestedParams: Map<String, Any>,
    val selectedTool: String,
    val selectedParams: Map<String, Any>,
    val reasoning: String? = null,
    val wasModified: Boolean = false
) {
    companion object {
        /**
         * Create decision info from suggested and selected tool calls.
         */
        fun from(
            intent: String,
            suggestedTool: String,
            suggestedParams: Map<String, Any>,
            selectedTool: String,
            selectedParams: Map<String, Any>,
            reasoning: String? = null
        ): PlanDecisionInfo {
            val toolChanged = suggestedTool != selectedTool
            val paramsChanged = suggestedParams != selectedParams
            return PlanDecisionInfo(
                intent = intent,
                suggestedTool = suggestedTool,
                suggestedParams = suggestedParams,
                selectedTool = selectedTool,
                selectedParams = selectedParams,
                reasoning = reasoning,
                wasModified = toolChanged || paramsChanged
            )
        }
    }
}

/**
 * Stream type for summary generation
 */
enum class SummaryStreamType {
    STREAMING,      // Raw LLM summary chunks
    FORMATTED,      // Formatted with metadata (step, tools, duration)
    COMPLETE        // Final chunk
}

/**
 * Streaming response from StepSummarizer.
 *
 * @param type Type of chunk
 * @param delta New content in this chunk (for STREAMING)
 * @param rawSummary Raw summary from LLM
 * @param formattedSummary Summary with metadata formatting
 * @param isComplete True if streaming is complete
 */
data class SummaryStreamResponse(
    val type: SummaryStreamType,
    val delta: String = "",
    val rawSummary: String = "",
    val formattedSummary: String = "",
    val isComplete: Boolean = false
)

/**
 * Execution phase for unified step execution streaming
 */
enum class ExecutionPhase {
    PLANNING,      // StepPlanner generating tool call
    EXECUTING,     // ToolExecutor running tools
    SUMMARIZING,   // StepSummarizer generating summary
    COMPLETE       // All done
}

/**
 * Streaming response for unified step execution.
 *
 * Emits chunks through all phases:
 * 1. PLANNING phase (step planning streaming)
 * 2. EXECUTING phase (tool execution)
 * 3. SUMMARIZING phase (summary generation streaming)
 * 4. COMPLETE phase (final)
 *
 * @param phase Current execution phase
 * @param streamContent Streaming content (for PLANNING/SUMMARIZING)
 * @param plan Execution plan (set during PLANNING)
 * @param executionResult Result from tool execution (set during EXECUTING)
 * @param summary Generated summary (set during SUMMARIZING)
 * @param isComplete True if this phase is complete
 * @param error Error details if operation failed
 */
data class StepExecutionStreamResponse(
    val phase: ExecutionPhase,
    val streamContent: String = "",
    val plan: ExecutionPlan? = null,
    val executionResult: ToolExecutionResult? = null,
    val summary: String = "",
    val isComplete: Boolean,
    val error: ErrorDetail? = null
)

/**
 * Execution plan for a step
 */
data class ExecutionPlan(
    val tools: List<ToolCallSpec>,
    val description: String,
    val estimatedDurationMs: Long,
    val dependencies: List<String>,
    val planDecision: PlanDecisionInfo? = null
)

/**
 * Result from tool execution
 */
data class ToolExecutionResult(
    val success: Boolean,
    val output: String,
    val filesChanged: List<String> = emptyList(),
    val metadata: Map<String, Any> = emptyMap()
)

/**
 * Error details for failed operations
 */
data class ErrorDetail(
    val code: String,
    val message: String,
    val details: Map<String, Any>? = null
)