package pl.jclab.refio.services.session

import pl.jclab.refio.api.models.Message
import pl.jclab.refio.api.models.ToolCallDisplayInfo
import pl.jclab.refio.api.models.ToolCallResult
import pl.jclab.refio.api.models.ToolCallStatus
import pl.jclab.refio.api.models.ToolDisplayType
import pl.jclab.refio.core.api.CoreApiRouter
import pl.jclab.refio.core.db.ToolCallData
import pl.jclab.refio.services.logging.dualLogger
import java.util.UUID

class MessageDispatcher(
    private val projectRouter: CoreApiRouter,
    private val stateManager: SessionStateManager
) {

    private val logger = dualLogger("MessageDispatcher")

    suspend fun loadMessages() {
        val currentSession = stateManager.getActiveSession() ?: return
        try {
            logger.info { "[MESSAGES] loadMessages start: taskId=${currentSession.id}" }

            val existingSystemMessages = stateManager.messages.value.filter { msg ->
                msg.role == "system" && msg.taskId == currentSession.id
            }
            val response = projectRouter.chatRouter.getMessages(currentSession.id)
            logger.info { "[MESSAGES] loadMessages response: taskId=${currentSession.id}, count=${response.count}" }
            val toolResultPathByToolCallId = response.messages
                .mapNotNull { coreMsg ->
                    if (coreMsg.role != "tool" || coreMsg.toolCallId.isNullOrBlank()) return@mapNotNull null
                    val path = extractPathFromMetadata(coreMsg.metadata) ?: return@mapNotNull null
                    coreMsg.toolCallId!! to path
                }
                .toMap()

            // Build toolCallId → tool result content map for inline display
            val toolResultByToolCallId = response.messages
                .filter { it.role == "tool" && !it.toolCallId.isNullOrBlank() }
                .associateBy(
                    { it.toolCallId!! },
                    { ToolResultSummary(
                        content = it.content,
                        isSummarized = it.isSummarized,
                        rawOutput = it.rawOutput
                    ) }
                )
            // Track which tool results have been inlined into tool call bubbles
            val inlinedToolCallIds = mutableSetOf<String>()

            val dbMessages = response.messages.flatMap { coreMsg ->
                val assistantEnvelope = if (coreMsg.role == "assistant") {
                    parseAssistantJsonEnvelope(coreMsg.content)
                } else {
                    null
                }
                val hasActions = assistantEnvelope?.hasActions == true

                // Normalize assistant content for display:
                // - unwrap {"content":"..."} / {"response":"..."}
                // - preserve true plan JSON for plan bubble rendering
                // - filter tool-call protocol blocks
                val cleanContent = if (coreMsg.role == "assistant") {
                    normalizeAssistantDisplayContent(coreMsg.content, assistantEnvelope)
                } else {
                    coreMsg.content
                }

                // Parse toolCallInfo from metadata OR toolCallsJson
                val toolCallInfo = enrichToolCallInfo(
                    info = parseToolCallInfo(coreMsg.metadata, coreMsg.toolCallsJson),
                    toolResultPathByToolCallId = toolResultPathByToolCallId,
                    toolResultByToolCallId = toolResultByToolCallId,
                    inlinedToolCallIds = inlinedToolCallIds
                )

                // Diagnostic log for action envelopes generated by AgentTurnLoop.
                if (hasActions) {
                    logger.info {
                        "[PLAN_DEBUG] Message with actions: isPlan=${assistantEnvelope?.isPlanJson == true}, " +
                            "hasToolCalls=${!coreMsg.toolCallsJson.isNullOrBlank()}, " +
                            "toolCallInfo=$toolCallInfo, " +
                            "contentPreview=${coreMsg.content.take(100)}"
                    }
                }
                val finalContent = cleanContent

                // Handle empty assistant messages with tool calls
                if (coreMsg.role == "assistant" && finalContent.isBlank()) {
                    // Has toolCallsJson - create tool call display messages for ALL tool calls
                    if (!coreMsg.toolCallsJson.isNullOrBlank()) {
                        val allToolCalls = parseAllToolCallsFromJson(coreMsg.toolCallsJson)
                        if (!allToolCalls.isNullOrEmpty()) {
                            return@flatMap allToolCalls.mapIndexed { index, tc ->
                                val enriched = enrichToolCallInfo(
                                    info = tc,
                                    toolResultPathByToolCallId = toolResultPathByToolCallId,
                                    toolResultByToolCallId = toolResultByToolCallId,
                                    inlinedToolCallIds = inlinedToolCallIds
                                ) ?: tc
                                createToolCallDisplayMessage(
                                    id = if (index == 0) coreMsg.id else "${coreMsg.id}:tc$index",
                                    taskId = coreMsg.taskId,
                                    createdAt = coreMsg.createdAt,
                                    toolCallInfo = enriched
                                )
                            }
                        }
                    }

                    // Has TOOL_CALL: in content (legacy format)
                    if (coreMsg.content.contains("TOOL_CALL:") && coreMsg.metadata.isNullOrBlank()) {
                        return@flatMap emptyList()
                    }

                    // Has metadata with tool_call type - render as tool call bubble
                    if (toolCallInfo != null) {
                        return@flatMap listOf(
                            createToolCallDisplayMessage(
                                id = coreMsg.id,
                                taskId = coreMsg.taskId,
                                createdAt = coreMsg.createdAt,
                                toolCallInfo = toolCallInfo,
                                metadata = coreMsg.metadata
                            )
                        )
                    }

                    // Completely empty - filter out
                    if (coreMsg.metadata.isNullOrBlank()) {
                        return@flatMap emptyList()
                    }
                }

                val toolDisplay = ToolMessageDisplayResolver.resolve(
                    role = coreMsg.role,
                    content = finalContent,
                    isSummarized = coreMsg.isSummarized,
                    rawOutput = coreMsg.rawOutput
                )
                val displayContent = toolDisplay.content

                val displayMessage = Message(
                    id = coreMsg.id,
                    taskId = coreMsg.taskId,
                    role = coreMsg.role,
                    content = displayContent,
                    thinking = coreMsg.thinking,  // Reasoning process from gpt-oss, Claude
                    tokensIn = coreMsg.tokensIn,
                    tokensOut = coreMsg.tokensOut,
                    costUsd = coreMsg.cost,
                    createdAt = coreMsg.createdAt,
                    metadata = if (toolCallInfo != null && coreMsg.metadata.isNullOrBlank()) {
                        ToolCallDisplayInfo.toMetadataJson(toolCallInfo)
                    } else {
                        coreMsg.metadata
                    },
                    toolCallId = coreMsg.toolCallId, // For TOOL messages - link to tool call
                    toolCallInfo = toolCallInfo,
                    toolStreamContent = toolDisplay.toolStreamContent,
                    agentName = (coreMsg as? pl.jclab.refio.core.api.MessageResponse)?.agentName,
                    agentDepth = (coreMsg as? pl.jclab.refio.core.api.MessageResponse)?.agentDepth
                )

                // Skip tool result messages whose content is already inlined into the tool call bubble
                if (coreMsg.role == "tool" && !coreMsg.toolCallId.isNullOrBlank()
                    && coreMsg.toolCallId in inlinedToolCallIds) {
                    return@flatMap emptyList()
                }

                if (coreMsg.role == "assistant" && toolCallInfo != null && displayContent.isNotBlank()) {
                    val allToolCalls = parseAllToolCallsFromJson(coreMsg.toolCallsJson)
                    val toolCallMessages = if (!allToolCalls.isNullOrEmpty()) {
                        allToolCalls.mapIndexed { index, tc ->
                            val enriched = enrichToolCallInfo(
                                info = tc,
                                toolResultPathByToolCallId = toolResultPathByToolCallId,
                                toolResultByToolCallId = toolResultByToolCallId,
                                inlinedToolCallIds = inlinedToolCallIds
                            ) ?: tc
                            createToolCallDisplayMessage(
                                id = "${coreMsg.id}:tc$index",
                                taskId = coreMsg.taskId,
                                createdAt = coreMsg.createdAt,
                                toolCallInfo = enriched
                            )
                        }
                    } else {
                        listOf(
                            createToolCallDisplayMessage(
                                id = "${coreMsg.id}:toolcall",
                                taskId = coreMsg.taskId,
                                createdAt = coreMsg.createdAt,
                                toolCallInfo = toolCallInfo
                            )
                        )
                    }
                    listOf(
                        displayMessage.copy(
                            metadata = null,
                            toolCallInfo = null
                        )
                    ) + toolCallMessages
                } else {
                    listOf(displayMessage)
                }
            }

            val dbMessageIds = dbMessages.map { it.id }.toSet()
            val inMemoryOnlySystemMessages = existingSystemMessages.filterNot { it.id in dbMessageIds }
            // DB already returns messages ordered by createdAt ASC, id ASC.
            // Preserve that order and keep UI-only system messages appended in their current order
            // so reloads do not reshuffle bubbles after streaming finishes.
            val allMessages = dbMessages + inMemoryOnlySystemMessages

            val currentMessages = stateManager.messages.value
            if (!areMessagesEqual(currentMessages, allMessages)) {
                stateManager.updateMessages { allMessages }
                logger.info {
                    "[MESSAGES] Loaded: db=${dbMessages.size}, inMemory=${inMemoryOnlySystemMessages.size}, " +
                        "taskId=${currentSession.id}"
                }
            } else {
                logger.debug { "[MESSAGES] Unchanged, skipping update (count=${allMessages.size})" }
            }
        } catch (e: Exception) {
            logger.error(e) { "Failed to load messages" }
        }
    }

    /**
     * Parse ToolCallDisplayInfo from metadata JSON or toolCallsJson.
     * Prioritizes metadata (already formatted) over toolCallsJson (raw tool calls).
     */
    private fun parseToolCallInfo(metadata: String?, toolCallsJson: String?): ToolCallDisplayInfo? {
        val metadataInfo = if (!metadata.isNullOrBlank()) {
            ToolCallDisplayInfo.fromMetadataJson(metadata)
        } else {
            null
        }
        val toolCallsInfo = parseToolCallInfoFromToolCallsJson(toolCallsJson)

        return when {
            metadataInfo != null && toolCallsInfo != null -> mergeToolCallInfo(
                primary = metadataInfo,
                fallback = toolCallsInfo
            )
            metadataInfo != null -> metadataInfo
            else -> toolCallsInfo
        }
    }

    private fun parseToolCallInfoFromToolCallsJson(toolCallsJson: String?): ToolCallDisplayInfo? {
        return parseAllToolCallsFromJson(toolCallsJson)?.firstOrNull()
    }

    /**
     * Parse ALL tool calls from toolCallsJson (not just the first one).
     * Used to create separate display messages for each tool call in multi-tool-call messages.
     */
    private fun parseAllToolCallsFromJson(toolCallsJson: String?): List<ToolCallDisplayInfo>? {
        if (toolCallsJson.isNullOrBlank()) return null
        val toolCalls = ToolCallData.fromJsonList(toolCallsJson)
        if (toolCalls.isNullOrEmpty()) return null

        return toolCalls.map { call ->
            ToolCallDisplayInfo(
                toolName = call.name,
                toolCallId = call.id,
                displayType = inferDisplayType(call.name),
                parameters = parseToolArguments(call.arguments),
                status = ToolCallStatus.COMPLETED
            )
        }
    }

    private fun mergeToolCallInfo(primary: ToolCallDisplayInfo, fallback: ToolCallDisplayInfo): ToolCallDisplayInfo {
        val mergedParams = linkedMapOf<String, String>()
        val keys = LinkedHashSet<String>()
        keys.addAll(primary.parameters.keys)
        keys.addAll(fallback.parameters.keys)

        keys.forEach { key ->
            val primaryValue = primary.parameters[key]
            val fallbackValue = fallback.parameters[key]
            mergedParams[key] = when {
                !primaryValue.isNullOrBlank() -> primaryValue
                !fallbackValue.isNullOrBlank() -> fallbackValue
                primaryValue != null -> primaryValue
                fallbackValue != null -> fallbackValue
                else -> ""
            }
        }

        return primary.copy(
            toolName = if (primary.toolName.isBlank()) fallback.toolName else primary.toolName,
            toolCallId = if (primary.toolCallId.isBlank()) fallback.toolCallId else primary.toolCallId,
            parameters = mergedParams
        )
    }

    private data class ToolResultSummary(
        val content: String,
        val isSummarized: Boolean,
        val rawOutput: String?
    )

    private fun enrichToolCallInfo(
        info: ToolCallDisplayInfo?,
        toolResultPathByToolCallId: Map<String, String>,
        toolResultByToolCallId: Map<String, ToolResultSummary> = emptyMap(),
        inlinedToolCallIds: MutableSet<String> = mutableSetOf()
    ): ToolCallDisplayInfo? {
        if (info == null) return null
        if (info.toolCallId.isBlank()) return info

        var enriched = info

        // Enrich with path from tool result metadata
        if (PATH_KEYS.none { !info.parameters[it].isNullOrBlank() }) {
            val recoveredPath = toolResultPathByToolCallId[info.toolCallId]
            if (recoveredPath != null) {
                val enrichedParameters = LinkedHashMap(enriched.parameters)
                enrichedParameters["path"] = recoveredPath
                enriched = enriched.copy(parameters = enrichedParameters)
            }
        }

        // Enrich with tool result content (for inline display in tool call bubble)
        if (enriched.result == null) {
            val toolResult = toolResultByToolCallId[info.toolCallId]
            if (toolResult != null && toolResult.content.isNotBlank()) {
                val summary = createCompactResultSummary(toolResult.content, info.toolName)
                enriched = enriched.copy(
                    result = ToolCallResult(
                        success = enriched.status == ToolCallStatus.COMPLETED,
                        summary = summary
                    )
                )
                inlinedToolCallIds.add(info.toolCallId)
            }
        }

        return enriched
    }

    /**
     * Create a compact summary of tool result for inline display.
     * Truncates long output to a single descriptive line.
     */
    private fun createCompactResultSummary(content: String, toolName: String): String {
        val trimmed = content.trim()
        if (trimmed.isBlank()) return ""

        // For short content, use as-is
        if (trimmed.length <= 120) return trimmed

        // Count meaningful lines for multi-line results
        val lines = trimmed.lines().filter { it.isNotBlank() }
        return when {
            toolName in setOf("file_search", "read_directory") -> {
                val fileCount = lines.size
                val firstFiles = lines.take(3).joinToString(", ") { it.trim().substringAfterLast('/') }
                if (fileCount > 3) "$firstFiles... ($fileCount results)" else firstFiles
            }
            toolName == "grep_search" -> {
                "${lines.size} matches found"
            }
            toolName == "read_file" -> {
                "${lines.size} lines read"
            }
            toolName == "run_terminal_command" -> {
                val preview = lines.take(2).joinToString(" ").take(100)
                if (lines.size > 2) "$preview... (${lines.size} lines)" else preview
            }
            else -> {
                val preview = trimmed.take(100).replace('\n', ' ')
                if (trimmed.length > 100) "$preview..." else preview
            }
        }
    }

    private fun extractPathFromMetadata(metadata: String?): String? {
        if (metadata.isNullOrBlank()) return null
        return try {
            val metadataMap = com.google.gson.Gson().fromJson(
                metadata,
                com.google.gson.reflect.TypeToken.get(Map::class.java).type
            ) as? Map<*, *> ?: return null

            PATH_KEYS.firstNotNullOfOrNull { key ->
                metadataMap[key]?.toString()?.takeIf { it.isNotBlank() }
            }
        } catch (_: Exception) {
            null
        }
    }

    companion object {
        private val PATH_KEYS = listOf("path", "file", "file_path", "filepath", "target_path", "target_file")
    }

    private fun createToolCallDisplayMessage(
        id: String,
        taskId: String,
        createdAt: Long,
        toolCallInfo: ToolCallDisplayInfo,
        metadata: String? = ToolCallDisplayInfo.toMetadataJson(toolCallInfo)
    ): Message {
        return Message(
            id = id,
            taskId = taskId,
            role = "assistant",
            content = "",
            toolCallInfo = toolCallInfo,
            createdAt = createdAt,
            metadata = metadata
        )
    }

    private data class AssistantJsonEnvelope(
        val hasActions: Boolean,
        val hasEmptyActions: Boolean,
        val isPlanJson: Boolean,
        val textPayload: String?
    )

    private fun parseAssistantJsonEnvelope(content: String): AssistantJsonEnvelope? {
        val trimmed = content.trim()
        if (!trimmed.startsWith("{") || !trimmed.endsWith("}")) return null

        return try {
            val root = com.google.gson.JsonParser.parseString(trimmed).asJsonObject
            val hasActions = root.has("actions") && root.get("actions").isJsonArray
            val hasEmptyActions = hasActions && root.getAsJsonArray("actions").size() == 0
            val isPlanJson = root.has("plan") || root.has("subtasks")
            val contentField = getJsonString(root, "content")
            val responseField = getJsonString(root, "response")
            val rawPayload = contentField?.takeIf { it.isNotBlank() } ?: responseField?.takeIf { it.isNotBlank() }
            val payload = rawPayload?.let { ToolCallContentSanitizer.unwrapNestedPayload(it) }
            AssistantJsonEnvelope(
                hasActions = hasActions,
                hasEmptyActions = hasEmptyActions,
                isPlanJson = isPlanJson,
                textPayload = payload
            )
        } catch (_: Exception) {
            null
        }
    }

    private fun getJsonString(json: com.google.gson.JsonObject, key: String): String? {
        if (!json.has(key)) return null
        val element = json.get(key)
        return if (element.isJsonPrimitive && element.asJsonPrimitive.isString) {
            element.asString
        } else {
            null
        }
    }

    private fun normalizeAssistantDisplayContent(
        rawContent: String,
        envelope: AssistantJsonEnvelope?
    ): String {
        if (envelope?.isPlanJson == true) {
            return rawContent
        }

        val textPayload = envelope?.textPayload
        if (!textPayload.isNullOrBlank()) {
            return textPayload
        }

        if (envelope?.hasEmptyActions == true) {
            return "Task completed. No further actions required."
        }

        // Hide raw action envelopes from chat; tool bubbles and TOOL results
        // already provide execution details.
        if (envelope?.hasActions == true) {
            return ""
        }

        return ToolCallContentSanitizer.sanitize(rawContent)
    }

    /**
     * Infer display type from tool name.
     */
    private fun inferDisplayType(toolName: String): ToolDisplayType {
        return when (toolName) {
            "advance_code_editing", "multi_line_editor" -> ToolDisplayType.LLM_EDIT
            "code_editing", "create_new_file", "multi_edit" -> ToolDisplayType.CODE_EDIT
            "run_terminal_command" -> ToolDisplayType.TERMINAL
            else -> ToolDisplayType.SIMPLE
        }
    }

    /**
     * Parse tool arguments JSON to Map<String, String>.
     */
    private fun parseToolArguments(argumentsJson: String): Map<String, String> {
        return try {
            val args = com.google.gson.Gson().fromJson(
                argumentsJson, com.google.gson.reflect.TypeToken.get(Map::class.java).type
            ) as? Map<*, *> ?: return emptyMap()

            args.entries.mapNotNull { (key, value) ->
                val keyString = key as? String ?: return@mapNotNull null
                keyString to (value?.toString() ?: "")
            }.toMap()
        } catch (e: Exception) {
            logger.warn(e) { "Failed to parse tool arguments JSON" }
            emptyMap()
        }
    }

    suspend fun answerQuestion(questionId: String, answer: String) {
        logger.info {
            "[MESSAGES] Answering orchestrator question: questionId=$questionId, answerChars=${answer.length}"
        }

        try {
            val currentSession = stateManager.getActiveSession()
                ?: throw IllegalStateException("No active session")

            val userMessage = Message(
                id = UUID.randomUUID().toString(),
                taskId = currentSession.id,
                role = "user",
                content = answer,
                createdAt = System.currentTimeMillis()
            )
            stateManager.appendMessage(userMessage)

            projectRouter.userInteraction.provideResponse(questionId, answer)

            logger.info { "[MESSAGES] Answer recorded, orchestration will resume" }
        } catch (e: Exception) {
            logger.error(e) { "Failed to answer question: $questionId" }
            throw e
        }
    }

    /**
     * Filter out TOOL_CALL blocks from assistant message content.
     * These are internal protocol markers that shouldn't be shown to users.
     * The "Executing:" system messages provide user-friendly tool execution display.
     *
     * IMPORTANT: Does NOT filter plan JSON (which has "plan" or "subtasks" fields).
     * Plan JSON should be preserved for ChatView specialized bubble rendering.
     */
    private fun areMessagesEqual(current: List<Message>, new: List<Message>): Boolean {
        if (current.size != new.size) return false
        return current.zip(new).all { (a, b) ->
            a.id == b.id &&
                a.role == b.role &&
                a.content == b.content &&
                a.tokensIn == b.tokensIn &&
                a.tokensOut == b.tokensOut &&
                a.costUsd == b.costUsd &&
                a.createdAt == b.createdAt &&
                a.metadata == b.metadata &&
                a.isStreaming == b.isStreaming
        }
    }
}
