package pl.jclab.refio.core.api

import pl.jclab.refio.core.llm.LLMUsage

/**
 * Streaming API models for chat streaming (US-027)
 *
 * Based on specification in docs/0027-stream-chat.md
 *
 * Note: StreamChunk is now defined in StreamTypes.kt (RFC 0032)
 */

/**
 * Streaming API models for Plan/Agent mode streaming (ADR-0031)
 *
 * Based on specification in docs/0031-stream-agent.md
 */

/**
 * Tool call specification from step planning
 */
data class ToolCallSpec(
    val name: String,
    val params: Map<String, Any>,
    val expectedOutput: String? = null
)

/**
 * Details about planning decision - what was suggested vs what was selected by LLM.
 *
 * Provides transparency into how LLM modified the initial suggestion:
 * - intent: High-level description of what step should achieve
 * - suggestedTool: Tool name from PlanningService (initial plan)
 * - suggestedParams: Parameters from initial plan
 * - selectedTool: Tool name chosen by LLM (may differ)
 * - selectedParams: Parameters generated by LLM (may differ)
 * - reasoning: LLM's explanation for any changes (if modified)
 * - wasModified: True if LLM changed tool or params from suggestion
 */
data class PlanDecisionInfo(
    val intent: String,
    val suggestedTool: String,
    val suggestedParams: Map<String, Any>,
    val selectedTool: String,
    val selectedParams: Map<String, Any>,
    val reasoning: String? = null,
    val wasModified: Boolean = false
) {
    companion object {
        /**
         * Create decision info from suggested and selected tool calls.
         */
        fun from(
            intent: String,
            suggestedTool: String,
            suggestedParams: Map<String, Any>,
            selectedTool: String,
            selectedParams: Map<String, Any>,
            reasoning: String? = null
        ): PlanDecisionInfo {
            val toolChanged = suggestedTool != selectedTool
            val paramsChanged = suggestedParams != selectedParams
            return PlanDecisionInfo(
                intent = intent,
                suggestedTool = suggestedTool,
                suggestedParams = suggestedParams,
                selectedTool = selectedTool,
                selectedParams = selectedParams,
                reasoning = reasoning,
                wasModified = toolChanged || paramsChanged
            )
        }
    }
}

