package pl.jclab.refio.cli

import pl.jclab.refio.core.config.ConfigKeys
import pl.jclab.refio.core.db.TaskStatus

/**
 * Exit-code contract for headless / multi-agent runs.
 *
 * The process exits 0 only when the work actually succeeded, so a CI step gating on the
 * process exit code sees a non-delivering or failed run as a failure. A failed, incomplete
 * or errored run returns a non-zero code.
 */
internal object HeadlessExit {
    const val SUCCESS = 0
    const val FAILURE = 1

    /** SUCCESS only for a delivered turn; FAILED / INCOMPLETE / anything else is non-zero. */
    fun forStatus(status: TaskStatus): Int =
        if (status == TaskStatus.SUCCESS) SUCCESS else FAILURE
}

/**
 * Fold the `--no-egress` switch into the run-scope config overrides used by the headless and
 * multi-agent paths.
 *
 * no-egress is enforced by reading `general.no_egress_enabled` (the egress gate plus the LLM
 * callers), so a headless run must surface the flag through that same config key. The flag is
 * otherwise dropped on the headless path (it only reaches the interactive TUI). When the flag
 * is absent the overrides are returned untouched, so the configured / UI default still applies.
 */
internal fun withNoEgress(base: Map<String, String>, noEgress: Boolean): Map<String, String> =
    if (noEgress) base + (ConfigKeys.GENERAL_NO_EGRESS_ENABLED.key to "true") else base

/**
 * Fold `--model` into the run-scope overrides as `ui.selected_model` so a headless `--model X` is
 * authoritative for EVERY model slot (turn, coding/editing, plan, subagents), matching the intuitive
 * "use X everywhere" semantics.
 *
 * Without this, `--model` sets only the turn LLM (the turn request's model); the editing tools
 * (`advance_code_editing` / `multi_line_editor`), plan, and subagents resolve their model via
 * `ModelSelectionService.getModel(...)`, which reads `ui.selected_model` (which overrides every slot)
 * then `default_model.<slot>` and never sees `--model` - so file content could be generated by a
 * different model than the one named on the command line. An explicit `--config ui.selected_model=...`
 * still wins (a user-set value is never overwritten); a blank or absent `--model` leaves overrides intact.
 */
internal fun withSelectedModel(base: Map<String, String>, model: String?): Map<String, String> =
    if (!model.isNullOrBlank() && !base.containsKey(ConfigKeys.UI_SELECTED_MODEL.key)) {
        base + (ConfigKeys.UI_SELECTED_MODEL.key to model)
    } else {
        base
    }
