package pl.jclab.refio.services.session

import pl.jclab.refio.api.models.Message
import pl.jclab.refio.api.models.ToolCallDisplayInfo
import pl.jclab.refio.api.models.ToolCallStatus
import pl.jclab.refio.api.models.ToolDisplayType
import pl.jclab.refio.core.api.CoreApiRouter
import pl.jclab.refio.core.db.ToolCallData
import pl.jclab.refio.services.logging.dualLogger
import java.util.UUID

class MessageDispatcher(
    private val projectRouter: CoreApiRouter,
    private val stateManager: SessionStateManager
) {

    private val logger = dualLogger("MessageDispatcher")

    suspend fun loadMessages() {
        val currentSession = stateManager.getActiveSession() ?: return
        try {
            logger.info { "[MESSAGES] loadMessages start: taskId=${currentSession.id}" }

            val existingSystemMessages = stateManager.messages.value.filter { msg ->
                msg.role == "system" && msg.taskId == currentSession.id
            }
            val response = projectRouter.getMessages(currentSession.id)
            logger.info { "[MESSAGES] loadMessages response: taskId=${currentSession.id}, count=${response.count}" }
            val toolResultPathByToolCallId = response.messages
                .mapNotNull { coreMsg ->
                    if (coreMsg.role != "tool" || coreMsg.toolCallId.isNullOrBlank()) return@mapNotNull null
                    val path = extractPathFromMetadata(coreMsg.metadata) ?: return@mapNotNull null
                    coreMsg.toolCallId to path
                }
                .toMap()

            val dbMessages = response.messages.mapNotNull { coreMsg ->
                val assistantEnvelope = if (coreMsg.role == "assistant") {
                    parseAssistantJsonEnvelope(coreMsg.content)
                } else {
                    null
                }
                val hasActions = assistantEnvelope?.hasActions == true

                // Normalize assistant content for display:
                // - unwrap {"content":"..."} / {"response":"..."}
                // - preserve true plan JSON for plan bubble rendering
                // - filter tool-call protocol blocks
                val cleanContent = if (coreMsg.role == "assistant") {
                    normalizeAssistantDisplayContent(coreMsg.content, assistantEnvelope)
                } else {
                    coreMsg.content
                }

                // Parse toolCallInfo from metadata OR toolCallsJson
                val toolCallInfo = enrichToolCallInfo(
                    info = parseToolCallInfo(coreMsg.metadata, coreMsg.toolCallsJson),
                    toolResultPathByToolCallId = toolResultPathByToolCallId
                )

                // Diagnostic log for action envelopes generated by AgentTurnLoop.
                if (hasActions) {
                    logger.info {
                        "[PLAN_DEBUG] Message with actions: isPlan=${assistantEnvelope?.isPlanJson == true}, " +
                            "hasToolCalls=${!coreMsg.toolCallsJson.isNullOrBlank()}, " +
                            "toolCallInfo=$toolCallInfo, " +
                            "contentPreview=${coreMsg.content.take(100)}"
                    }
                }
                val finalContent = cleanContent

                // Handle empty assistant messages with tool calls
                if (coreMsg.role == "assistant" && finalContent.isBlank()) {
                    // Has toolCallsJson - create tool call display message
                    if (!coreMsg.toolCallsJson.isNullOrBlank() && toolCallInfo != null) {
                        return@mapNotNull Message(
                            id = coreMsg.id,
                            taskId = coreMsg.taskId,
                            role = coreMsg.role,
                            content = "",
                            toolCallInfo = toolCallInfo,
                            createdAt = coreMsg.createdAt,
                            metadata = ToolCallDisplayInfo.toMetadataJson(toolCallInfo)
                        )
                    }

                    // Has TOOL_CALL: in content (legacy format)
                    if (coreMsg.content.contains("TOOL_CALL:") && coreMsg.metadata.isNullOrBlank()) {
                        return@mapNotNull null
                    }

                    // Has metadata with tool_call type - render as tool call bubble
                    if (toolCallInfo != null) {
                        return@mapNotNull Message(
                            id = coreMsg.id,
                            taskId = coreMsg.taskId,
                            role = coreMsg.role,
                            content = "",
                            toolCallInfo = toolCallInfo,
                            createdAt = coreMsg.createdAt,
                            metadata = coreMsg.metadata
                        )
                    }

                    // Completely empty - filter out
                    if (coreMsg.metadata.isNullOrBlank()) {
                        return@mapNotNull null
                    }
                }

                // For TOOL messages with summarized content and rawOutput available,
                // use rawOutput for display (shows full generated code instead of summary)
                val displayContent = if (coreMsg.role == "tool" &&
                    coreMsg.isSummarized &&
                    !coreMsg.rawOutput.isNullOrBlank()) {
                    coreMsg.rawOutput
                } else {
                    finalContent
                }

                Message(
                    id = coreMsg.id,
                    taskId = coreMsg.taskId,
                    role = coreMsg.role,
                    content = displayContent,
                    thinking = coreMsg.thinking,  // Reasoning process from gpt-oss, Claude
                    tokensIn = coreMsg.tokensIn,
                    tokensOut = coreMsg.tokensOut,
                    costUsd = coreMsg.cost,
                    createdAt = coreMsg.createdAt,
                    metadata = if (toolCallInfo != null && coreMsg.metadata.isNullOrBlank()) {
                        ToolCallDisplayInfo.toMetadataJson(toolCallInfo)
                    } else {
                        coreMsg.metadata
                    },
                    toolCallId = coreMsg.toolCallId, // For TOOL messages - link to tool call
                    toolCallInfo = toolCallInfo,
                    // Store rawOutput in toolStreamContent for UI to access original full output
                    toolStreamContent = if (coreMsg.role == "tool" && coreMsg.isSummarized) {
                        coreMsg.rawOutput
                    } else {
                        null
                    }
                )
            }

            val dbMessageIds = dbMessages.map { it.id }.toSet()
            val inMemoryOnlySystemMessages = existingSystemMessages.filterNot { it.id in dbMessageIds }
            val allMessages = (dbMessages + inMemoryOnlySystemMessages).sortedBy { it.createdAt }

            val currentMessages = stateManager.messages.value
            if (!areMessagesEqual(currentMessages, allMessages)) {
                stateManager.updateMessages { allMessages }
                logger.info {
                    "[MESSAGES] Loaded: db=${dbMessages.size}, inMemory=${inMemoryOnlySystemMessages.size}, " +
                        "taskId=${currentSession.id}"
                }
            } else {
                logger.debug { "[MESSAGES] Unchanged, skipping update (count=${allMessages.size})" }
            }
        } catch (e: Exception) {
            logger.error(e) { "Failed to load messages" }
        }
    }

    /**
     * Parse ToolCallDisplayInfo from metadata JSON or toolCallsJson.
     * Prioritizes metadata (already formatted) over toolCallsJson (raw tool calls).
     */
    private fun parseToolCallInfo(metadata: String?, toolCallsJson: String?): ToolCallDisplayInfo? {
        val metadataInfo = if (!metadata.isNullOrBlank()) {
            ToolCallDisplayInfo.fromMetadataJson(metadata)
        } else {
            null
        }
        val toolCallsInfo = parseToolCallInfoFromToolCallsJson(toolCallsJson)

        return when {
            metadataInfo != null && toolCallsInfo != null -> mergeToolCallInfo(
                primary = metadataInfo,
                fallback = toolCallsInfo
            )
            metadataInfo != null -> metadataInfo
            else -> toolCallsInfo
        }
    }

    private fun parseToolCallInfoFromToolCallsJson(toolCallsJson: String?): ToolCallDisplayInfo? {
        if (toolCallsJson.isNullOrBlank()) return null
        val toolCalls = ToolCallData.fromJsonList(toolCallsJson)
        if (toolCalls.isNullOrEmpty()) return null

        val firstCall = toolCalls.first()
        return ToolCallDisplayInfo(
            toolName = firstCall.name,
            toolCallId = firstCall.id,
            displayType = inferDisplayType(firstCall.name),
            parameters = parseToolArguments(firstCall.arguments),
            status = ToolCallStatus.COMPLETED
        )
    }

    private fun mergeToolCallInfo(primary: ToolCallDisplayInfo, fallback: ToolCallDisplayInfo): ToolCallDisplayInfo {
        val mergedParams = linkedMapOf<String, String>()
        val keys = LinkedHashSet<String>()
        keys.addAll(primary.parameters.keys)
        keys.addAll(fallback.parameters.keys)

        keys.forEach { key ->
            val primaryValue = primary.parameters[key]
            val fallbackValue = fallback.parameters[key]
            mergedParams[key] = when {
                !primaryValue.isNullOrBlank() -> primaryValue
                !fallbackValue.isNullOrBlank() -> fallbackValue
                primaryValue != null -> primaryValue
                fallbackValue != null -> fallbackValue
                else -> ""
            }
        }

        return primary.copy(
            toolName = if (primary.toolName.isBlank()) fallback.toolName else primary.toolName,
            toolCallId = if (primary.toolCallId.isBlank()) fallback.toolCallId else primary.toolCallId,
            parameters = mergedParams
        )
    }

    private fun enrichToolCallInfo(
        info: ToolCallDisplayInfo?,
        toolResultPathByToolCallId: Map<String, String>
    ): ToolCallDisplayInfo? {
        if (info == null) return null
        if (info.toolCallId.isBlank()) return info
        if (PATH_KEYS.any { !info.parameters[it].isNullOrBlank() }) return info

        val recoveredPath = toolResultPathByToolCallId[info.toolCallId] ?: return info
        val enrichedParameters = LinkedHashMap(info.parameters)
        enrichedParameters["path"] = recoveredPath
        return info.copy(parameters = enrichedParameters)
    }

    private fun extractPathFromMetadata(metadata: String?): String? {
        if (metadata.isNullOrBlank()) return null
        return try {
            val metadataMap = com.google.gson.Gson().fromJson(
                metadata,
                com.google.gson.reflect.TypeToken.get(Map::class.java).type
            ) as? Map<*, *> ?: return null

            PATH_KEYS.firstNotNullOfOrNull { key ->
                metadataMap[key]?.toString()?.takeIf { it.isNotBlank() }
            }
        } catch (_: Exception) {
            null
        }
    }

    companion object {
        private val PATH_KEYS = listOf("path", "file", "file_path", "filepath", "target_path", "target_file")
    }

    private data class AssistantJsonEnvelope(
        val hasActions: Boolean,
        val hasEmptyActions: Boolean,
        val isPlanJson: Boolean,
        val textPayload: String?
    )

    private fun parseAssistantJsonEnvelope(content: String): AssistantJsonEnvelope? {
        val trimmed = content.trim()
        if (!trimmed.startsWith("{") || !trimmed.endsWith("}")) return null

        return try {
            val root = com.google.gson.JsonParser.parseString(trimmed).asJsonObject
            val hasActions = root.has("actions") && root.get("actions").isJsonArray
            val hasEmptyActions = hasActions && root.getAsJsonArray("actions").size() == 0
            val isPlanJson = root.has("plan") || root.has("subtasks")
            val contentField = getJsonString(root, "content")
            val responseField = getJsonString(root, "response")
            val payload = contentField?.takeIf { it.isNotBlank() } ?: responseField?.takeIf { it.isNotBlank() }
            AssistantJsonEnvelope(
                hasActions = hasActions,
                hasEmptyActions = hasEmptyActions,
                isPlanJson = isPlanJson,
                textPayload = payload
            )
        } catch (_: Exception) {
            null
        }
    }

    private fun getJsonString(json: com.google.gson.JsonObject, key: String): String? {
        if (!json.has(key)) return null
        val element = json.get(key)
        return if (element.isJsonPrimitive && element.asJsonPrimitive.isString) {
            element.asString
        } else {
            null
        }
    }

    private fun normalizeAssistantDisplayContent(
        rawContent: String,
        envelope: AssistantJsonEnvelope?
    ): String {
        if (envelope?.isPlanJson == true) {
            return rawContent
        }

        val textPayload = envelope?.textPayload
        if (!textPayload.isNullOrBlank()) {
            return textPayload
        }

        if (envelope?.hasEmptyActions == true) {
            return "Task completed. No further actions required."
        }

        // Hide raw action envelopes from chat; tool bubbles and TOOL results
        // already provide execution details.
        if (envelope?.hasActions == true) {
            return ""
        }

        return filterToolCallBlocks(rawContent)
    }

    /**
     * Infer display type from tool name.
     */
    private fun inferDisplayType(toolName: String): ToolDisplayType {
        return when (toolName) {
            "advance_code_editing", "multi_line_editor" -> ToolDisplayType.LLM_EDIT
            "code_editing", "create_new_file", "multi_edit" -> ToolDisplayType.CODE_EDIT
            "run_terminal_command" -> ToolDisplayType.TERMINAL
            else -> ToolDisplayType.SIMPLE
        }
    }

    /**
     * Parse tool arguments JSON to Map<String, String>.
     */
    private fun parseToolArguments(argumentsJson: String): Map<String, String> {
        return try {
            val args = com.google.gson.Gson().fromJson(
                argumentsJson, com.google.gson.reflect.TypeToken.get(Map::class.java).type
            ) as? Map<*, *> ?: return emptyMap()

            args.entries.mapNotNull { (key, value) ->
                val keyString = key as? String ?: return@mapNotNull null
                keyString to (value?.toString() ?: "")
            }.toMap()
        } catch (e: Exception) {
            logger.warn(e) { "Failed to parse tool arguments JSON" }
            emptyMap()
        }
    }

    suspend fun answerQuestion(questionId: String, answer: String) {
        logger.info {
            "[MESSAGES] Answering orchestrator question: questionId=$questionId, answerChars=${answer.length}"
        }

        try {
            val currentSession = stateManager.getActiveSession()
                ?: throw IllegalStateException("No active session")

            val userMessage = Message(
                id = UUID.randomUUID().toString(),
                taskId = currentSession.id,
                role = "user",
                content = answer,
                createdAt = System.currentTimeMillis()
            )
            stateManager.appendMessage(userMessage)

            projectRouter.userInteraction.provideResponse(questionId, answer)

            logger.info { "[MESSAGES] Answer recorded, orchestration will resume" }
        } catch (e: Exception) {
            logger.error(e) { "Failed to answer question: $questionId" }
            throw e
        }
    }

    /**
     * Filter out TOOL_CALL blocks from assistant message content.
     * These are internal protocol markers that shouldn't be shown to users.
     * The "Executing:" system messages provide user-friendly tool execution display.
     *
     * IMPORTANT: Does NOT filter plan JSON (which has "plan" or "subtasks" fields).
     * Plan JSON should be preserved for ChatView specialized bubble rendering.
     */
    private fun filterToolCallBlocks(content: String): String {
        // Check if content is a plan JSON (has "plan" or "subtasks")
        // Plans should not be filtered - they need to be displayed in ChatView
        val isPlan = isPlanJson(content)
        if (content.contains("\"actions\"")) {
            logger.info {
                "[FILTER_DEBUG] filterToolCallBlocks: isPlan=$isPlan, " +
                    "contentPreview=${content.take(100)}"
            }
        }
        if (isPlan) {
            return content
        }

        val patterns = listOf(
            Regex("""TOOL_CALL:\s*\w+\s*(?:\n|\r\n)?ARGUMENTS:\s*\{[\s\S]*?\}""", RegexOption.MULTILINE),
            Regex("""Tool calls:\s*(?:\n|\r\n)?TOOL_CALL:[\s\S]*?(?=\n\n|\z)""", RegexOption.MULTILINE),
            Regex("""<tool_call>[\s\S]*?</tool_call>"""),
            Regex("""```\s*(?:tool|tool_call)[\s\S]*?```""")
        )

        var result = content
        patterns.forEach { pattern ->
            result = result.replace(pattern, "")
        }
        return result.trim()
    }

    /**
     * Detect if content is a plan JSON structure.
     * Plan JSON has:
     * - "plan" field with description
     * - "subtasks" array
     */
    private fun isPlanJson(content: String): Boolean {
        if (!content.trim().startsWith("{")) return false
        return try {
            val json = com.google.gson.Gson().fromJson(
                content,
                com.google.gson.reflect.TypeToken.get(Map::class.java).type
            ) as? Map<*, *> ?: return false

            json.containsKey("plan") ||
            json.containsKey("subtasks")
        } catch (e: Exception) {
            false
        }
    }

    private fun areMessagesEqual(current: List<Message>, new: List<Message>): Boolean {
        if (current.size != new.size) return false
        return current.zip(new).all { (a, b) ->
            a.id == b.id &&
                a.role == b.role &&
                a.content == b.content &&
                a.tokensIn == b.tokensIn &&
                a.tokensOut == b.tokensOut &&
                a.costUsd == b.costUsd &&
                a.createdAt == b.createdAt &&
                a.metadata == b.metadata &&
                a.isStreaming == b.isStreaming
        }
    }
}
